apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat-server
        image: ${DOCKER_REGISTRY}/chat-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: mongo-password
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: mongo-host
        - name: MONGO_PORT
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: mongo-port
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: jwt-secret
        - name: JWT_ISSUER
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: jwt-issuer
        - name: JWT_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: jwt-audience
        - name: JWT_REALM
          valueFrom:
            secretKeyRef:
              name: chat-server-secrets
              key: jwt-realm
---
apiVersion: v1
kind: Service
metadata:
  name: chat-server
spec:
  selector:
    app: chat-server
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer 