name: Deploy Backend

on:
  push:
    branches: [ master ]
    paths:
      - 'chat-server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Gradle
        run: |
          cd chat-server
          ./gradlew build
          
      - name: Build Docker image
        run: |
          cd chat-server
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/chat-server:${{ github.sha }} .
          
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/chat-server:${{ github.sha }}
          
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl set image deployment/chat-server chat-server=${{ secrets.DOCKER_REGISTRY }}/chat-server:${{ github.sha }} -n ${{ secrets.KUBE_NAMESPACE }} 